### ISSUE TITLE
能不用#作为标签么?这样会和连接的标签冲突

### ISSUE THREAD

**Issue by Xuyiycl** [sethyuan/logseq-plugin-ol#1]

**Comment by sethyuan** [comment]
和连接的标签冲突是什么意思？

**Comment by Xuyiycl** [comment]
> 
就是用#会自动被识别并创建这个page，

**Comment by sethyuan** [comment]
你说的应该是标签 (tag)，标签和page基本相同，你只要不在上面写内容是不会物理创建页面的。采用标签的原因是一个技术问题，目前在Logseq中这是唯一能够运用的手段。不过这对软件的使用也不会有什么影响了。

**Comment by Xuyiycl** [comment]
好吧，谢谢
