### ISSUE TITLE
Start counter from another number

### ISSUE THREAD

**Issue by candideu** [sethyuan/logseq-plugin-ol#10]
Hello! How can I start my list counter from another number besides 1?

**Comment by sethyuan** [comment]
Since this is a pure CSS solution, it can only be implemented by hard coding numbers. I added support for counters from `#.ol-2` to `#.ol-10`, I hope it's enough for you. If not, you can add more CSS to your `custom.css`.

**Comment by candideu** [comment]
@sethyuan That's perfect, but how do I implement it for nested lists?

![image](https://user-images.githubusercontent.com/55474996/221386508-9a613307-5caa-41b8-8dd5-c3be27823974.png)

**Comment by sethyuan** [comment]
Just added the same support for nested lists, but you use tags like `#.ol-nested-s2`, there is a `s` before the number. This is because `#.ol-nested-2` is already designed for another purpose (stop nesting after 2 levels).

**Comment by candideu** [comment]
Perfect, it works as intended, Thanks @sethyuan!
