### ISSUE TITLE
[FR] Leading zeroes option in CSS - for Johnny Decimal index

### ISSUE THREAD

**Issue by sparkles6452** [sethyuan/logseq-plugin-ol#11]
Dear @sethyuan ,

 - Thank you for your contributions and many great plugins for Logseq.

- I dabble a bit with home automation and scripts, but I am no programmer.

 - I have recently implemented the Johnny Decimal system (https://johnnydecimal.com/) - and I use Logseq to keep my index.

 - I believe the ol plugin is perfectly suited to automate creation of new numbers, however - this would require implementing leading zeroes to the css. 

 - I believe a solution is presented here:
https://stackoverflow.com/questions/10935965/nested-css-counters-with-leading-zeros

**Suggestion**:

Implement a tag - example #.ol-nested-JAC
J (for Johnny Decimal)
A = Area (0-9)
C = Category (0-9)

The counter would - based on what number you've put as AC - start counting AC.01, AC.02, AC.03 .... until AC.99.

**EXAMPLE**

Item 01 #.ol-nested-J01
  01.01 Title xyz
  01.02 Title fyi

Item 59 #.ol-nested-J59
  59.01 Title abc
  59.02 Title def

I don't know how to modify, implement or use git.
If this idea gains traction, perhaps you could assist in implementing.

Thank you, have a nice day.

**Comment by sethyuan** [comment]
Unfortunately, I don't have time to implement this. I'll leave this ticket open, in case some else is interested in its implementation.

**Comment by sparkles6452** [comment]
Closing this as I have found / gained experience wirh a viable work-around, short version; typing the number is efficient enough. It has the benefit of allowing markup/manipulation of the number itself - and exports are more consistent (even when not using the logseq-plugin-doc that is compatible with logseq-plugin-ol).
