### ISSUE TITLE
序号的圆圈太大 & 第一级内容如何标序号

### ISSUE THREAD

**Issue by hdg8087** [sethyuan/logseq-plugin-ol#2]
【1】圆圈序号的圆圈太大，大小和其它序号不成比例。建议把其它序号放大一点，同时把圆圈缩小。

【2】四级大纲处的 1、 序号样式的距离，离文字似乎比其它的序号更远。

【3】右括号那个样式，用的是英文的右括号，可否再增加一个中文的右括号呢？

【4】当切换成如下图2的主题时，主题样式和序号结合起来，不太和谐。当然喽，这是主题的问题，不是插件的问题。这里只是反映一下情况。

【5】第一级内容如何标序号？

![image](https://user-images.githubusercontent.com/71086865/163710632-32cf06a7-5c34-4c84-998a-ca99f5deb5e7.png)

<img width="551" alt="fdcf9e6d61790f11b105d9c1dc19370" src="https://user-images.githubusercontent.com/71086865/163712185-15cc2a86-5358-41f6-ae2d-0ca1ffb575a0.png">

**Comment by hdg8087** [comment]
1、  这个样式的距离，离文字也似乎比其它的序号远了一点。

**Comment by hdg8087** [comment]
核实了一下，我把所有插件都关掉，还是有上述第2点的效果。。。请教一下我怎么关掉这个效果呢？或者你可否优化一下这个地方？

**Comment by hdg8087** [comment]
/*------------------------------主结构样式---------------------------*/

:root{
  --ls-page-title-size:20px;   /* 页面标题字体的大小 */
  --ls-page-text-size:15px;    /* 正文字体的大小 */
  --ls-font-family: "Noto Sans SC", sans-serif;  /* 全局字体 */
  --ls-font-family: "Noto Sans SC", sans-serif; /* 全局字体 */
  --comment:white; 
  --white: var(--foreground);
  --white-hover: #f8f8f280;
  --red: #ff5555; 
  --orange: #ff9580; 
  --orange-hover: #b26859;
  --yellow: #ffff80;
  --green:  #8aff80;
  --purple: #9580ff;
  --purple-hover: #bf93f980;
  --cyan: #80ffea; 
  --cyan-hover: #8be9fd80;
  --pink: #ff80bf; 
  --pink-hover: #ff79c680; 
  --selection: #43475a;
  --ls-page-inline-code-color:pink;
  --ls-page-inline-code-bg-color:var(--background);
}

.block-content {
line-height:26px;
letter-spacing:0.5px;
}

h2.font-bold.text-lg{
  font:30px;
}

/*----------------------------去掉“最近使用”前面的点号--------------------*/

.left-sidebar-inner .favorites .page-icon, .left-sidebar-inner .recent .page-icon {
    display: none;
}

/*----------------------------修改PDF的背景色--------------------*/

#pdf-layout-container[data-theme=dark] .textLayer {
    background-color: #211b1b;
}

/*----------------------------我常用的颜色样式-------------------------*/

span.page-reference a.page-ref[data-ref*="提挈段"] {
    color:rgb(0,151,235);
}

span.page-reference a.page-ref[data-ref*="概念"] {
  color:springgreen;
  padding-bottom:3px;
}

span.page-reference a.page-ref[data-ref*="关键词"] {
  color:rgb(5,192,145);
  padding: 3px;
}

span.page-reference a.page-ref[data-ref*="重要1"] {
    color:rgb(164,181,182);
    text-decoration: none;
	border-bottom: 0.1px rgb(80,70,120) solid;
	padding-bottom: 3px;
	padding-bottom:2px;
}

span.page-reference a.page-ref[data-ref*="重要2"] {
    color:rgb(164,181,182);
    text-decoration: none;
	border-bottom: 0.1px #990033 solid;
	padding-bottom:3px;
	padding-bottom:2px;
}

span.page-reference a.page-ref[data-ref*="重要3"] {
    color:rgb(164,181,182);
    text-decoration: none;
	border-bottom: 0.1px rgb(181,137,0) solid;
	padding-bottom:3px;
	padding-bottom:2px;
}

span.page-reference a.page-ref[data-ref*="重要4"] {
   color:rgb(164,181,182);
    text-decoration: none;
	border-bottom: 0.1px gold solid;
	padding-bottom: 3px;
	padding-bottom:2px;
}


/*-------------------超链接样式 双链接颜色---------------------*/

.external-link {
    color:DodgerBlue;
    text-decoration: none;
	border-bottom: 1px solid;
	padding-bottom: 3px;
} /* 超链本身的字体颜色及下划线 */

a.external-link::after {
  content: '🔗';
  display: inline;
} /* 超链接的前面加一个符号 */

.external-link:hover{
  color:white;
} /* 光标放到链接上的显示效果 */

a.page-ref{color:salmon;}
.block-ref{
    text-decoration: none;
	border-bottom: 2px salmon dotted;
	padding-bottom: 3px;
} /* 双链按显示的颜色 */

.open-block-ref-link {
    background-color: var(--ls-page-properties-background-color);
    padding: 1px 4px;
    border-radius: 2px;
    opacity: 1;
    color: gold;
}/* 节点链接的数字颜色 */


/*-----------------------------------各级标题--------------------------*/

.cp__sidebar-main-content h1.title {
    padding-right: 15px;
    margin-bottom: 40px;
} /* 页面标题下外边距 */

.ls-block h1 {color:rgb(5,150,100);
  font-size:16.7px !important;
  margin:0.25em 0 !important; 
  font-weight:700 !important;
  } /* 标题字体和上外边距，要加important，不然优先级不够 */

.ls-block h2 {color:rgb(5,150,100);
  font-size:16px !important;
  margin:0.15em 0 !important; 
  font-family:微软雅黑;
  font-weight:700 !important;
  } /* 以前1级标题是文档标题，现在是页面的1级标题 */

.ls-block h3 {color:#45b97c;
  font-size:15px !important;
  margin:0.1em 0 !important; 
  font-family:微软雅黑;
  font-weight:400 !important;
  } 

.editor-inner .h2, .editor-inner .h3, .ls-block :is(h2,h3) {
    border-bottom: 0px;
    margin: .4em 0 0;
} /* 只让一级标题下面有横线，其它级别的标题下面没有 */


/*--------------------------行内代码 代码块---------------------------*/

:not(pre)>code{
    padding: 0 4px !important;
    margin: 0 2px !important;
    color:rgb(164,181,182);
    background-color:rgb(38,50,56);
    vertical-align: text-bottom;
} /* 行内代码的样式：外边距、字体颜色、背景颜色 */

.cp__right-sidebar pre.CodeMirror-line { 
    background: #272822; 
    color: #f8f8f2;   
} /* 右侧栏代码块的背景色和文字颜色 */

html[data-theme="dark"] .CodeMirror {
  border: 8px solid rgb(2,54,67);
} /* 代码块的边框 */

html[data-theme="dark"] .CodeMirror span.cm-comment {
  color:rgb(164,181,182);
  font-style:normal;
} /* 代码块的注释 */

html[data-theme="dark"] .CodeMirror {   
  background-color: rgb(0,43,54);
  color: #EEFFFF;
} /* 代码块的背景 */

.cm-s-solarized .cm-number {  
  color:rgb(200,200,0);
} /* 代码中的数字 */

.cm-s-solarized .cm-keyword {
    color:#6495ED;
} /* 代码中的keyword */

.cm-s-solarized .cm-builtin {
    color: #D19275;
} /* 代码中的builtin */

.cm-s-solarized .cm-operator {
    color: rgb(220,120,220);
} /* 代码中的加减乘除等运算操作符 */

.cp__right-sidebar pre.CodeMirror-line {
  background-color: unset;
}  /* 右侧代码有默认的背景色，此3行代码将它的背景色改成左侧这样的 */

html[data-theme="dark"] .cm-s-default .CodeMirror-gutters {
  background: blue;
  color: #546E7A;
  border: none;
}

html[data-theme="dark"] .cm-s-default .CodeMirror-guttermarker,
html[data-theme="dark"] .cm-s-default .CodeMirror-guttermarker-subtle,
html[data-theme="dark"] .cm-s-default .CodeMirror-linenumber {
  color: #546E7A;
}

html[data-theme="dark"] .cm-s-default .CodeMirror-cursor {
  border-left: 1px solid #FFCC00;
}

html[data-theme="dark"] .cm-s-default div.CodeMirror-selected {
  background: rgba(128, 203, 196, 0.2);
}

html[data-theme="dark"] .cm-s-default.CodeMirror-focused div.CodeMirror-selected {
  background: rgba(128, 203, 196, 0.2);
}

html[data-theme="dark"] .cm-s-default .CodeMirror-line::selection,
html[data-theme="dark"] .cm-s-default .CodeMirror-line>span::selection,
html[data-theme="dark"] .cm-s-default .CodeMirror-line>span>span::selection {
  background: rgba(128, 203, 196, 0.2);
}

html[data-theme="dark"] .cm-s-default .CodeMirror-line::-moz-selection,
html[data-theme="dark"] .cm-s-default .CodeMirror-line>span::-moz-selection,
html[data-theme="dark"] .cm-s-default .CodeMirror-line>span>span::-moz-selection {
  background: rgba(128, 203, 196, 0.2);
}

html[data-theme="dark"] .cm-s-default .CodeMirror-activeline-background {
  background: rgba(0, 0, 0, 0.5);
}

html[data-theme="dark"] .cm-s-default .cm-variable-2 {
  color: #EEFFFF;
}

html[data-theme="dark"] .cm-s-default .cm-variable-3,
.cm-s-default .cm-type {
  color: #f07178;
}

html[data-theme="dark"] .cm-s-default .cm-atom {
  color: #F78C6C;
}

html[data-theme="dark"] .cm-s-default .cm-def {
  color: #82AAFF;
}
html[data-theme="dark"] .cm-s-default .cm-string {
  color: #C3E88D;
}
html[data-theme="dark"] .cm-s-default .cm-string-2 {
  color: #f07178;
}

html[data-theme="dark"] .cm-s-default .cm-variable {
  color: #f07178;
}
html[data-theme="dark"] .cm-s-default .cm-tag {
  color: #FF5370;
}
html[data-theme="dark"] .cm-s-default .cm-meta {
  color: #FFCB6B;
}
html[data-theme="dark"] .cm-s-default .cm-attribute {
  color: #C792EA;
}
html[data-theme="dark"] .cm-s-default .cm-property {
  color: #C792EA;
}
html[data-theme="dark"] .cm-s-default .cm-qualifier {
  color: #DECB6B;
}
html[data-theme="dark"] .cm-s-default .cm-variable-3,
html[data-theme="dark"] .cm-s-default .cm-type {
  color: #DECB6B;
}
html[data-theme="dark"] .cm-s-default .cm-error {
  color: rgba(255, 255, 255, 1.0);
  background-color: #FF5370;
}
html[data-theme="dark"] .cm-s-default .CodeMirror-matchingbracket {
  text-decoration: underline;
  color: white !important;
}


/*---------------------------标签样式设置-----------------------------*/

a.tag {
    font-size:16px;
    color:yellow;
    text-decoration: none;
} /*普通标签的显示样式*/

.tag:hover {
  color:white;
} /*光标放到标签上显示出的样式*/


/*---------------------------斜体 粗体 高亮----------------------------*/
i {color: var(--yellow);}
b {color:SkyBlue;}
mark {background-color: yellow);

**Comment by sethyuan** [comment]
我尽量依次回答一下吧。

1. 这个大小设置是为了能很好的容纳下两位数的序号，如果你不喜欢这个样式可以换一个或者自行改CSS。
2. 顿号引起的视觉错误。
3. 可以自行通过CSS定义你自己喜欢的序号符号，参考下面我给出的CSS代码。
4. 我更新了版本，基本兼容了Bullet Threading插件，你可以试试看。
5. 这个目前没有好的方法实现，欢迎提PR。

自定义有序列表符号示例代码：

```css
.ls-block[data-refs-self*='".ol-right-paren'] > .block-children-container > .block-children > .ls-block > div > div > a + a > .bullet-container::before {
  content: counter(kef-ol) ") ";
}

.ls-block[data-refs-self*='".ol-nested-right-paren'] > .block-children-container > .block-children > .ls-block > div > div > a + a > .bullet-container::before,
.ls-block[data-refs-self*='".ol-nested-right-paren'] .ls-block > div > div > a + a > .bullet-container::before {
  content: counters(kef-ol-nested, ".") ") ";
}
```

第一段对应普通列表，`.ol-right-paren`部分可以改为任何以`ol-`开头的tag，例如：`.ol-my`；`content`里面的双引号里的内容就是序号采用的符号，你可以按照喜好修改。

第二段对应嵌套列表，修改方法同第一段。
