### ISSUE TITLE
请求第一级可以使用

### ISSUE THREAD

**Issue by seyeeL** [sethyuan/logseq-plugin-ol#3]

**Comment by sethyuan** [comment]
我花了不少时间调研，结论是没发现有特别好的实现方法。

有一种不算特别好的方法，就是在page tags中加`.ol`之类的tags，类似在block中的识别方式。但是在首页（连续的日记页面）由于Logseq自身的问题无法拿到该信息，另外一般一级都是heading一类的内容，目前受Logseq DOM结构的限制，序号无法跟随内容文字的大小变化，会导致序号相对于标题很小，这样显示效果不好。

如果大家有好的方案的话我们可以在这里讨论。

**Comment by flython** [comment]
> 我花了不少时间调研，结论是没发现有特别好的实现方法。
> 
> 有一种不算特别好的方法，就是在page tags中加`.ol`之类的tags，类似在block中的识别方式。但是在首页（连续的日记页面）由于Logseq自身的问题无法拿到该信息，另外一般一级都是heading一类的内容，目前受Logseq DOM结构的限制，序号无法跟随内容文字的大小变化，会导致序号相对于标题很小，这样显示效果不好。
> 
> 如果大家有好的方案的话我们可以在这里讨论。

不知道大佬有没有demo或者记录可以指导下这里是怎么实现的，后端仔，想要研究一下，效果差也没关系

**Comment by sethyuan** [comment]
Logseq 官方实现了number list（快捷键 t n），第一级也是可用的，现在推荐直接用官方方案了。插件目前想实现这点还是很困难。这个issue我就先关了。

**Comment by flython** [comment]
> Logseq 官方实现了number list（快捷键 t n），第一级也是可用的，现在推荐直接用官方方案了。插件目前想实现这点还是很困难。这个issue我就先关了。

官方这个abcde没有插件的1.1.1.2这样好用，但是更新后继续用插件的数字太长会超界TAT

**Comment by sethyuan** [comment]
@flython 这个是CSS的问题，有空我研究下。

**Comment by sethyuan** [comment]
> > Logseq 官方实现了number list（快捷键 t n），第一级也是可用的，现在推荐直接用官方方案了。插件目前想实现这点还是很困难。这个issue我就先关了。
> 
> 官方这个abcde没有插件的1.1.1.2这样好用，但是更新后继续用插件的数字太长会超界TAT

我用最新版插件又试了一下，应该已经是兼容的了。你是用的最新版本的插件吗？

![image](https://github.com/sethyuan/logseq-plugin-ol/assets/3410293/4d53dc13-c5cc-47ce-aead-286c1e477340)
