### ISSUE TITLE
序号样式与列表统一

### ISSUE THREAD

**Issue by sstiger1230** [sethyuan/logseq-plugin-ol#4]
谢谢非常好用，又实用的插件！

添加列表序号后，如果列表本身设置了标题样式等，例如 /h3 三级列表，这个时候序号如果也能够显示为 h3 就完美统一了。
![image](https://user-images.githubusercontent.com/15171715/172033594-ce844f41-2be3-4ad2-8af4-ec70461dbb95.png)

例如，列表一、列表二是 h3三级列表，前面的序号显示效果就不匹配了

**Comment by sstiger1230** [comment]
看到了另外一个issues中的回复，期待日后有好的解决办法。

**Comment by sethyuan** [comment]
好消息，由于W3C在不断推进Web相关技术的发展，现在的浏览器也变的越来越能干了，所以序号样式匹配列表样式也变的可能了，不过目前还是只有最新的Chrome 105才支持，等后面Logseq更新了Electron版本我就尝试实现一下。

**Comment by sstiger1230** [comment]
好消息，期待

**Comment by sethyuan** [comment]
@sstiger1230  Electron终于升级了，我将这个功能实现了。
