### ISSUE TITLE
嵌套列表 (Nested List)需要增加一种样式，与论文的格式相似

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-ol#5]
嵌套列表 (Nested List)

#.ol-nested
#.ol-nested-right-paren

个人觉得需要增加一种样式，与论文的格式相似
#.ol-nested-with-space

就是以下所示

1  两个空格
1.1  两个空格
1.1.1  两个空格

**Comment by sethyuan** [comment]
可以参照README加自己喜欢的序号风格。
