### ISSUE TITLE
Plugin is installed multiple times

### ISSUE THREAD

**Issue by gioknx** [sethyuan/logseq-plugin-ol#6]
The idea of this plugin is great, but when I try to install:
![image](https://user-images.githubusercontent.com/6156710/188291759-3f4adf30-3699-4c17-b8b9-a404dbd9eb8f.png)

And because of this:
![image](https://user-images.githubusercontent.com/6156710/188291775-d9cdabe2-835b-4f13-ac8a-227b60bcec39.png)

And after a few minutes (while I was writing this message) this appeared:
![image](https://user-images.githubusercontent.com/6156710/188291753-d898b876-e56a-4eea-8c7f-8be26775e4cf.png)

**Comment by sethyuan** [comment]
Never had this reported, did you install the plugin with the marketplace?

**Comment by gioknx** [comment]
> Never had this reported, did you install the plugin with the marketplace?

Yes, installed it for the first time yesterday

**Comment by sethyuan** [comment]
I'm thinking it's a bug in Logseq, can you make a report there.
