### ISSUE TITLE
与PDF Export Plugin插件如何配合

### ISSUE THREAD

**Issue by sstiger1230** [sethyuan/logseq-plugin-ol#7]
现在Logseq本身没有PDF导出功能，都在使用PDF Export Plugin插件，但是导出时没有显示正确列表，不知道有没有什么方法？

**Comment by sethyuan** [comment]
两个办法：

1. 给PDF Export Plugin的作者说下这个情况，看可能是什么原因导致的。
2. 用DocView Exporter插件，这个插件是我写的，可以原样导出HTML文件（以看起来更像普通文档的形式），然后你用Chrome或Safari这种浏览器打印成PDF就可以了。打印的时候记得勾选下图选项，可以完美支持样式。另外你还可以操纵HTML来调整PDF的输出。

<img width="331" alt="image" src="https://user-images.githubusercontent.com/3410293/195304407-7b3e37ab-6352-4143-b41d-a5cb7fe50983.png">

**Comment by sstiger1230** [comment]
非常感谢！
