### ISSUE TITLE
set a depth limit

### ISSUE THREAD

**Issue by astubbs** [sethyuan/logseq-plugin-ol#8]
when tagging a block to be a nested ordered list, set a depth limit to auto auto stop at a nesting depth of say 2 - useful for large deep lists, so you don't have to add #.ul to each nested block beyond the desired depth.

**Comment by sethyuan** [comment]
Good idea! I added `#.ol-nested-2`, `#.ol-nested-3`, `#.ol-nested-right-paren-2` and `#.ol-nested-right-paren-3` to support for depth 2 and 3. Please try the new version. Is this enough?
